version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # mount Docker socket để Jenkins dùng được Docker
    user: root  # để Jenkins container có quyền dùng Docker

volumes:
  jenkins_home:
